load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "example3",
    srcs = ["main.cc"],
    deps = [
        "//examples/example3/lib1:lib1",
        "//examples/example3/lib2:lib2",
    ],
)
